### PR TITLE
README: make it even easier to test it out

### PR DESCRIPTION
**Pull request by unhammer**
since no one likes typing in throwaway passwords or having to read long manuals that might turn into dead links :)

### CODE REVIEW

**Comment by xich** [comment]
Leave the link as "For more, see [this guide]"?

Otherwise, lgtm.

**Comment by dmjio** [comment]
> Leave the link as "For more, see [this guide]"?
>
> Otherwise, lgtm.

ditto @xich

@unhammer could you rebase fixup the change ? o/w no big deal.

**Comment by unhammer** [comment]
I interpreted that as do "push --force", hope that was correct :)

**Comment by dmjio** [comment]
@unhammer, yes perfect. Rebase then force push. Thanks :clinking_glasses:

**Pull request merged**
